// <auto-generated />
using System;
using Akros.Htp.Vendor.Backend.DataAccess.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Akros.Htp.Vendor.Backend.DataAccess.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20211014194830_Database_v6")]
    partial class Database_v6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Akros.Htp.Vendor.Backend.DataAccess.Model.Booking.BookingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BookedFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("BookedTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Akros.Htp.Vendor.Backend.DataAccess.Model.Hotel.HotelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Homepage")
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Entity");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            City = "Hamburg",
                            Country = "Germany",
                            Name = "Billiges Hotel",
                            Price = 0,
                            Stars = 1,
                            ZipCode = "20251"
                        },
                        new
                        {
                            Id = 2L,
                            City = "Sursee",
                            Country = "Switzerland",
                            Name = "Schoenes Hotel",
                            Price = 0,
                            Stars = 3,
                            ZipCode = "6210"
                        },
                        new
                        {
                            Id = 3L,
                            City = "Sursee",
                            Country = "Switzerland",
                            Name = "Luxus Hotel",
                            Price = 0,
                            Stars = 5,
                            ZipCode = "6210"
                        },
                        new
                        {
                            Id = 4L,
                            City = "Bern",
                            Country = "Switzerland",
                            Name = ".Net Hotel Bern",
                            Price = 0,
                            Stars = 3,
                            ZipCode = "8401"
                        });
                });

            modelBuilder.Entity("Akros.Htp.Vendor.Backend.DataAccess.Model.Image.ImageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AlternativeText")
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Image")
                        .HasColumnType("smallint");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<byte>("ThumbImage")
                        .HasColumnType("smallint");

                    b.Property<string>("ThumbImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AlternativeText = "Bild 1",
                            Height = 200,
                            HotelId = 1L,
                            Image = (byte)0,
                            ImageUrl = "http://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-2.48c60181.jpeg",
                            ThumbImage = (byte)0,
                            ThumbImageUrl = "http://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-2.48c60181.jpeg",
                            Title = "Bild 1",
                            Width = 200
                        },
                        new
                        {
                            Id = 2L,
                            AlternativeText = "Bild 1",
                            Height = 200,
                            HotelId = 2L,
                            Image = (byte)0,
                            ImageUrl = "https://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-6.3697aea3.jpeg",
                            ThumbImage = (byte)0,
                            ThumbImageUrl = "https://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-6.3697aea3.jpeg",
                            Title = "Bild 1",
                            Width = 200
                        },
                        new
                        {
                            Id = 3L,
                            AlternativeText = "Bild 1",
                            Height = 200,
                            HotelId = 3L,
                            Image = (byte)0,
                            ImageUrl = "https://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-11.1605f19e.jpeg",
                            ThumbImage = (byte)0,
                            ThumbImageUrl = "https://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-11.1605f19e.jpeg",
                            Title = "Bild 1",
                            Width = 200
                        },
                        new
                        {
                            Id = 4L,
                            AlternativeText = "Bild 1",
                            Height = 200,
                            HotelId = 4L,
                            Image = (byte)0,
                            ImageUrl = "https://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-11.1605f19e.jpeg",
                            ThumbImage = (byte)0,
                            ThumbImageUrl = "https://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-11.1605f19e.jpeg",
                            Title = "Bild 1",
                            Width = 200
                        },
                        new
                        {
                            Id = 5L,
                            AlternativeText = "Bild 2",
                            Height = 200,
                            HotelId = 4L,
                            Image = (byte)0,
                            ImageUrl = "https://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-6.3697aea3.jpeg",
                            ThumbImage = (byte)0,
                            ThumbImageUrl = "https://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-6.3697aea3.jpeg",
                            Title = "Bild 2",
                            Width = 200
                        },
                        new
                        {
                            Id = 6L,
                            AlternativeText = "Bild 3",
                            Height = 200,
                            HotelId = 4L,
                            Image = (byte)0,
                            ImageUrl = "http://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-2.48c60181.jpeg",
                            ThumbImage = (byte)0,
                            ThumbImageUrl = "http://htp-vendor-hotel1-ui.azurewebsites.net/static/media/room-2.48c60181.jpeg",
                            Title = "Bild 3",
                            Width = 200
                        });
                });

            modelBuilder.Entity("Akros.Htp.Vendor.Backend.DataAccess.Model.Room.RoomEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<long>("HotelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 1L,
                            Name = "RoomNumber0",
                            Price = 1552,
                            Type = 0
                        },
                        new
                        {
                            Id = 2L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 2L,
                            Name = "RoomNumber1",
                            Price = 818,
                            Type = 0
                        },
                        new
                        {
                            Id = 3L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 3L,
                            Name = "RoomNumber2",
                            Price = 83,
                            Type = 0
                        },
                        new
                        {
                            Id = 4L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 3L,
                            Name = "RoomNumber3",
                            Price = 1789,
                            Type = 0
                        },
                        new
                        {
                            Id = 5L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 1L,
                            Name = "RoomNumber4",
                            Price = 1054,
                            Type = 0
                        },
                        new
                        {
                            Id = 6L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 2L,
                            Name = "RoomNumber5",
                            Price = 320,
                            Type = 0
                        },
                        new
                        {
                            Id = 7L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 3L,
                            Name = "RoomNumber6",
                            Price = 2026,
                            Type = 0
                        },
                        new
                        {
                            Id = 8L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 1L,
                            Name = "RoomNumber7",
                            Price = 1291,
                            Type = 0
                        },
                        new
                        {
                            Id = 9L,
                            Currency = 0,
                            Floor = 9,
                            HotelId = 2L,
                            Name = "RoomNumber8",
                            Price = 557,
                            Type = 0
                        },
                        new
                        {
                            Id = 10L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 3L,
                            Name = "RoomNumber9",
                            Price = 2262,
                            Type = 0
                        },
                        new
                        {
                            Id = 11L,
                            Currency = 0,
                            Floor = 9,
                            HotelId = 1L,
                            Name = "RoomNumber10",
                            Price = 1528,
                            Type = 0
                        },
                        new
                        {
                            Id = 12L,
                            Currency = 0,
                            Floor = 5,
                            HotelId = 2L,
                            Name = "RoomNumber11",
                            Price = 793,
                            Type = 0
                        },
                        new
                        {
                            Id = 13L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 2L,
                            Name = "RoomNumber12",
                            Price = 2499,
                            Type = 0
                        },
                        new
                        {
                            Id = 14L,
                            Currency = 0,
                            Floor = 5,
                            HotelId = 3L,
                            Name = "RoomNumber13",
                            Price = 1764,
                            Type = 0
                        },
                        new
                        {
                            Id = 15L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 1L,
                            Name = "RoomNumber14",
                            Price = 1030,
                            Type = 0
                        },
                        new
                        {
                            Id = 16L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 2L,
                            Name = "RoomNumber15",
                            Price = 295,
                            Type = 0
                        },
                        new
                        {
                            Id = 17L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 3L,
                            Name = "RoomNumber16",
                            Price = 2001,
                            Type = 0
                        },
                        new
                        {
                            Id = 18L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 1L,
                            Name = "RoomNumber17",
                            Price = 1266,
                            Type = 0
                        },
                        new
                        {
                            Id = 19L,
                            Currency = 0,
                            Floor = 2,
                            HotelId = 2L,
                            Name = "RoomNumber18",
                            Price = 532,
                            Type = 0
                        },
                        new
                        {
                            Id = 20L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 3L,
                            Name = "RoomNumber19",
                            Price = 2237,
                            Type = 0
                        },
                        new
                        {
                            Id = 21L,
                            Currency = 0,
                            Floor = 2,
                            HotelId = 3L,
                            Name = "RoomNumber20",
                            Price = 1503,
                            Type = 0
                        },
                        new
                        {
                            Id = 22L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 1L,
                            Name = "RoomNumber21",
                            Price = 769,
                            Type = 0
                        },
                        new
                        {
                            Id = 23L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 2L,
                            Name = "RoomNumber22",
                            Price = 2474,
                            Type = 0
                        },
                        new
                        {
                            Id = 24L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 3L,
                            Name = "RoomNumber23",
                            Price = 1740,
                            Type = 0
                        },
                        new
                        {
                            Id = 25L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 1L,
                            Name = "RoomNumber24",
                            Price = 1005,
                            Type = 0
                        },
                        new
                        {
                            Id = 26L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 2L,
                            Name = "RoomNumber25",
                            Price = 271,
                            Type = 0
                        },
                        new
                        {
                            Id = 27L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 3L,
                            Name = "RoomNumber26",
                            Price = 1976,
                            Type = 0
                        },
                        new
                        {
                            Id = 28L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 1L,
                            Name = "RoomNumber27",
                            Price = 1242,
                            Type = 0
                        },
                        new
                        {
                            Id = 29L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 1L,
                            Name = "RoomNumber28",
                            Price = 507,
                            Type = 0
                        },
                        new
                        {
                            Id = 30L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 2L,
                            Name = "RoomNumber29",
                            Price = 2213,
                            Type = 0
                        },
                        new
                        {
                            Id = 31L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 3L,
                            Name = "RoomNumber30",
                            Price = 1478,
                            Type = 0
                        },
                        new
                        {
                            Id = 32L,
                            Currency = 0,
                            Floor = 9,
                            HotelId = 1L,
                            Name = "RoomNumber31",
                            Price = 744,
                            Type = 0
                        },
                        new
                        {
                            Id = 33L,
                            Currency = 0,
                            Floor = 5,
                            HotelId = 2L,
                            Name = "RoomNumber32",
                            Price = 2449,
                            Type = 0
                        },
                        new
                        {
                            Id = 34L,
                            Currency = 0,
                            Floor = 9,
                            HotelId = 3L,
                            Name = "RoomNumber33",
                            Price = 1715,
                            Type = 0
                        },
                        new
                        {
                            Id = 35L,
                            Currency = 0,
                            Floor = 5,
                            HotelId = 1L,
                            Name = "RoomNumber34",
                            Price = 980,
                            Type = 0
                        },
                        new
                        {
                            Id = 36L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 2L,
                            Name = "RoomNumber35",
                            Price = 246,
                            Type = 0
                        },
                        new
                        {
                            Id = 37L,
                            Currency = 0,
                            Floor = 5,
                            HotelId = 3L,
                            Name = "RoomNumber36",
                            Price = 1951,
                            Type = 0
                        },
                        new
                        {
                            Id = 38L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 3L,
                            Name = "RoomNumber37",
                            Price = 1217,
                            Type = 0
                        },
                        new
                        {
                            Id = 39L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 1L,
                            Name = "RoomNumber38",
                            Price = 483,
                            Type = 0
                        },
                        new
                        {
                            Id = 40L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 2L,
                            Name = "RoomNumber39",
                            Price = 2188,
                            Type = 0
                        },
                        new
                        {
                            Id = 41L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 3L,
                            Name = "RoomNumber40",
                            Price = 1454,
                            Type = 0
                        },
                        new
                        {
                            Id = 42L,
                            Currency = 0,
                            Floor = 2,
                            HotelId = 1L,
                            Name = "RoomNumber41",
                            Price = 719,
                            Type = 0
                        },
                        new
                        {
                            Id = 43L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 2L,
                            Name = "RoomNumber42",
                            Price = 2425,
                            Type = 0
                        },
                        new
                        {
                            Id = 44L,
                            Currency = 0,
                            Floor = 2,
                            HotelId = 3L,
                            Name = "RoomNumber43",
                            Price = 1690,
                            Type = 0
                        },
                        new
                        {
                            Id = 45L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 1L,
                            Name = "RoomNumber44",
                            Price = 956,
                            Type = 0
                        },
                        new
                        {
                            Id = 46L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 1L,
                            Name = "RoomNumber45",
                            Price = 221,
                            Type = 0
                        },
                        new
                        {
                            Id = 47L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 2L,
                            Name = "RoomNumber46",
                            Price = 1927,
                            Type = 0
                        },
                        new
                        {
                            Id = 48L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 3L,
                            Name = "RoomNumber47",
                            Price = 1192,
                            Type = 0
                        },
                        new
                        {
                            Id = 49L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 1L,
                            Name = "RoomNumber48",
                            Price = 458,
                            Type = 0
                        },
                        new
                        {
                            Id = 50L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 2L,
                            Name = "RoomNumber49",
                            Price = 2163,
                            Type = 0
                        },
                        new
                        {
                            Id = 51L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 3L,
                            Name = "RoomNumber50",
                            Price = 1429,
                            Type = 0
                        },
                        new
                        {
                            Id = 52L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 1L,
                            Name = "RoomNumber51",
                            Price = 694,
                            Type = 0
                        },
                        new
                        {
                            Id = 53L,
                            Currency = 0,
                            Floor = 9,
                            HotelId = 2L,
                            Name = "RoomNumber52",
                            Price = 2400,
                            Type = 0
                        },
                        new
                        {
                            Id = 54L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 2L,
                            Name = "RoomNumber53",
                            Price = 1665,
                            Type = 0
                        },
                        new
                        {
                            Id = 55L,
                            Currency = 0,
                            Floor = 9,
                            HotelId = 3L,
                            Name = "RoomNumber54",
                            Price = 931,
                            Type = 0
                        },
                        new
                        {
                            Id = 56L,
                            Currency = 0,
                            Floor = 5,
                            HotelId = 1L,
                            Name = "RoomNumber55",
                            Price = 197,
                            Type = 0
                        },
                        new
                        {
                            Id = 57L,
                            Currency = 0,
                            Floor = 9,
                            HotelId = 2L,
                            Name = "RoomNumber56",
                            Price = 1902,
                            Type = 0
                        },
                        new
                        {
                            Id = 58L,
                            Currency = 0,
                            Floor = 5,
                            HotelId = 3L,
                            Name = "RoomNumber57",
                            Price = 1168,
                            Type = 0
                        },
                        new
                        {
                            Id = 59L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 1L,
                            Name = "RoomNumber58",
                            Price = 433,
                            Type = 0
                        },
                        new
                        {
                            Id = 60L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 2L,
                            Name = "RoomNumber59",
                            Price = 2139,
                            Type = 0
                        },
                        new
                        {
                            Id = 61L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 3L,
                            Name = "RoomNumber60",
                            Price = 1404,
                            Type = 0
                        },
                        new
                        {
                            Id = 62L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 1L,
                            Name = "RoomNumber61",
                            Price = 670,
                            Type = 0
                        },
                        new
                        {
                            Id = 63L,
                            Currency = 0,
                            Floor = 2,
                            HotelId = 1L,
                            Name = "RoomNumber62",
                            Price = 2375,
                            Type = 0
                        },
                        new
                        {
                            Id = 64L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 2L,
                            Name = "RoomNumber63",
                            Price = 1641,
                            Type = 0
                        },
                        new
                        {
                            Id = 65L,
                            Currency = 0,
                            Floor = 2,
                            HotelId = 3L,
                            Name = "RoomNumber64",
                            Price = 906,
                            Type = 0
                        },
                        new
                        {
                            Id = 66L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 1L,
                            Name = "RoomNumber65",
                            Price = 172,
                            Type = 0
                        },
                        new
                        {
                            Id = 67L,
                            Currency = 0,
                            Floor = 2,
                            HotelId = 2L,
                            Name = "RoomNumber66",
                            Price = 1877,
                            Type = 0
                        },
                        new
                        {
                            Id = 68L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 3L,
                            Name = "RoomNumber67",
                            Price = 1143,
                            Type = 0
                        },
                        new
                        {
                            Id = 69L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 1L,
                            Name = "RoomNumber68",
                            Price = 408,
                            Type = 0
                        },
                        new
                        {
                            Id = 70L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 2L,
                            Name = "RoomNumber69",
                            Price = 2114,
                            Type = 0
                        },
                        new
                        {
                            Id = 71L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 2L,
                            Name = "RoomNumber70",
                            Price = 1380,
                            Type = 0
                        },
                        new
                        {
                            Id = 72L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 3L,
                            Name = "RoomNumber71",
                            Price = 645,
                            Type = 0
                        },
                        new
                        {
                            Id = 73L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 1L,
                            Name = "RoomNumber72",
                            Price = 2351,
                            Type = 0
                        },
                        new
                        {
                            Id = 74L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 2L,
                            Name = "RoomNumber73",
                            Price = 1616,
                            Type = 0
                        },
                        new
                        {
                            Id = 75L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 3L,
                            Name = "RoomNumber74",
                            Price = 882,
                            Type = 0
                        },
                        new
                        {
                            Id = 76L,
                            Currency = 0,
                            Floor = 9,
                            HotelId = 1L,
                            Name = "RoomNumber75",
                            Price = 147,
                            Type = 0
                        },
                        new
                        {
                            Id = 77L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 2L,
                            Name = "RoomNumber76",
                            Price = 1853,
                            Type = 0
                        },
                        new
                        {
                            Id = 78L,
                            Currency = 0,
                            Floor = 9,
                            HotelId = 3L,
                            Name = "RoomNumber77",
                            Price = 1118,
                            Type = 0
                        },
                        new
                        {
                            Id = 79L,
                            Currency = 0,
                            Floor = 5,
                            HotelId = 3L,
                            Name = "RoomNumber78",
                            Price = 384,
                            Type = 0
                        },
                        new
                        {
                            Id = 80L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 1L,
                            Name = "RoomNumber79",
                            Price = 2089,
                            Type = 0
                        },
                        new
                        {
                            Id = 81L,
                            Currency = 0,
                            Floor = 5,
                            HotelId = 2L,
                            Name = "RoomNumber80",
                            Price = 1355,
                            Type = 0
                        },
                        new
                        {
                            Id = 82L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 3L,
                            Name = "RoomNumber81",
                            Price = 620,
                            Type = 0
                        },
                        new
                        {
                            Id = 83L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 1L,
                            Name = "RoomNumber82",
                            Price = 2326,
                            Type = 0
                        },
                        new
                        {
                            Id = 84L,
                            Currency = 0,
                            Floor = 1,
                            HotelId = 2L,
                            Name = "RoomNumber83",
                            Price = 1591,
                            Type = 0
                        },
                        new
                        {
                            Id = 85L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 3L,
                            Name = "RoomNumber84",
                            Price = 857,
                            Type = 0
                        },
                        new
                        {
                            Id = 86L,
                            Currency = 0,
                            Floor = 2,
                            HotelId = 1L,
                            Name = "RoomNumber85",
                            Price = 122,
                            Type = 0
                        },
                        new
                        {
                            Id = 87L,
                            Currency = 0,
                            Floor = 6,
                            HotelId = 2L,
                            Name = "RoomNumber86",
                            Price = 1828,
                            Type = 0
                        },
                        new
                        {
                            Id = 88L,
                            Currency = 0,
                            Floor = 2,
                            HotelId = 2L,
                            Name = "RoomNumber87",
                            Price = 1094,
                            Type = 0
                        },
                        new
                        {
                            Id = 89L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 3L,
                            Name = "RoomNumber88",
                            Price = 359,
                            Type = 0
                        },
                        new
                        {
                            Id = 90L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 1L,
                            Name = "RoomNumber89",
                            Price = 2065,
                            Type = 0
                        },
                        new
                        {
                            Id = 91L,
                            Currency = 0,
                            Floor = 7,
                            HotelId = 2L,
                            Name = "RoomNumber90",
                            Price = 1330,
                            Type = 0
                        },
                        new
                        {
                            Id = 92L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 3L,
                            Name = "RoomNumber91",
                            Price = 596,
                            Type = 0
                        },
                        new
                        {
                            Id = 93L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 1L,
                            Name = "RoomNumber92",
                            Price = 2301,
                            Type = 0
                        },
                        new
                        {
                            Id = 94L,
                            Currency = 0,
                            Floor = 3,
                            HotelId = 2L,
                            Name = "RoomNumber93",
                            Price = 1567,
                            Type = 0
                        },
                        new
                        {
                            Id = 95L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 3L,
                            Name = "RoomNumber94",
                            Price = 832,
                            Type = 0
                        },
                        new
                        {
                            Id = 96L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 3L,
                            Name = "RoomNumber95",
                            Price = 98,
                            Type = 0
                        },
                        new
                        {
                            Id = 97L,
                            Currency = 0,
                            Floor = 8,
                            HotelId = 1L,
                            Name = "RoomNumber96",
                            Price = 1803,
                            Type = 0
                        },
                        new
                        {
                            Id = 98L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 2L,
                            Name = "RoomNumber97",
                            Price = 1069,
                            Type = 0
                        },
                        new
                        {
                            Id = 99L,
                            Currency = 0,
                            Floor = 9,
                            HotelId = 3L,
                            Name = "RoomNumber98",
                            Price = 334,
                            Type = 0
                        },
                        new
                        {
                            Id = 100L,
                            Currency = 0,
                            Floor = 5,
                            HotelId = 1L,
                            Name = "RoomNumber99",
                            Price = 2040,
                            Type = 0
                        },
                        new
                        {
                            Id = 101L,
                            Currency = 0,
                            Floor = 4,
                            HotelId = 4L,
                            Name = "Aareblick",
                            Price = 500,
                            Type = 8
                        },
                        new
                        {
                            Id = 102L,
                            Currency = 0,
                            Floor = 2,
                            HotelId = 4L,
                            Name = "Stadtblick",
                            Price = 300,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Akros.Htp.Vendor.Backend.DataAccess.Model.Booking.BookingEntity", b =>
                {
                    b.HasOne("Akros.Htp.Vendor.Backend.DataAccess.Model.Room.RoomEntity", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Akros.Htp.Vendor.Backend.DataAccess.Model.Image.ImageEntity", b =>
                {
                    b.HasOne("Akros.Htp.Vendor.Backend.DataAccess.Model.Hotel.HotelEntity", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Akros.Htp.Vendor.Backend.DataAccess.Model.Room.RoomEntity", b =>
                {
                    b.HasOne("Akros.Htp.Vendor.Backend.DataAccess.Model.Hotel.HotelEntity", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Akros.Htp.Vendor.Backend.DataAccess.Model.Room.RoomEntity", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
