
export const BOOKING_ROOM_STARTED = "BOOKING_ROOM_STARTED"
export const BOOKING_ROOM_SUCCEDED = "BOOKING_ROOM_SUCCEDED"
export const BOOKING_ROOM_FAILED = "BOOKING_ROOM_FAILED"

export const SET_VENDOR_TYPE = "SET_VENDOR_TYPE"
