DROP TABLE IF EXISTS country;
DROP TABLE IF EXISTS hotel;
DROP TABLE IF EXISTS facility;
DROP TABLE IF EXISTS facility_assignment;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS image;

CREATE TABLE country (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
code VARCHAR(4) NOT Null
);


CREATE TABLE hotel (
id BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
stars INT(1) NOT NULL,
homepage VARCHAR(200) NOT NULL,
house_number VARCHAR(120) NOT NULL,
street VARCHAR(120) NOT NULL,
city VARCHAR(50) NOT NULL,
zip_code VARCHAR(10) NOT NULL,
price INT NOT NULL,
country_id BIGINT NOT NULL
);


CREATE TABLE facility (
id BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL
) ;

CREATE TABLE facility_assignment (
id BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
facility_id BIGINT NOT NULL,
hotel_id BIGINT NOT NULL
) ;

CREATE TABLE room (
id BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
type VARCHAR(100) NOT NULL,
price INT NOT NULL,
hotel_id BIGINT NOT NULL
) ;

CREATE TABLE booking (
id BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
booked_from date NOT NULL,
booked_to date NOT NULL,
room_id BIGINT NOT NULL
) ;


CREATE TABLE image (
id BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
width INT NOT NULL,
height INT NOT NULL,
download_url VARCHAR(255) NOT NULL,
hotel_id BIGINT  NOT NULL
) ;
