/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Akros.Htp.Exchange.Model;
using Akros.Htp.Exchange.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Akros.Htp.Exchange.Test.Model
{
    /// <summary>
    ///  Class for testing BookingResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BookingResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BookingResponse
        //private BookingResponse instance;

        public BookingResponseTests()
        {
            // TODO uncomment below to create an instance of BookingResponse
            //instance = new BookingResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BookingResponse
        /// </summary>
        [Fact]
        public void BookingResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BookingResponse
            //Assert.IsType<BookingResponse>(instance);
        }


        /// <summary>
        /// Test the property 'RoomPaid'
        /// </summary>
        [Fact]
        public void RoomPaidTest()
        {
            // TODO unit test for the property 'RoomPaid'
        }
        /// <summary>
        /// Test the property 'DateFrom'
        /// </summary>
        [Fact]
        public void DateFromTest()
        {
            // TODO unit test for the property 'DateFrom'
        }
        /// <summary>
        /// Test the property 'DateTo'
        /// </summary>
        [Fact]
        public void DateToTest()
        {
            // TODO unit test for the property 'DateTo'
        }
        /// <summary>
        /// Test the property 'ResponseMessage'
        /// </summary>
        [Fact]
        public void ResponseMessageTest()
        {
            // TODO unit test for the property 'ResponseMessage'
        }
        /// <summary>
        /// Test the property 'ResponseStatus'
        /// </summary>
        [Fact]
        public void ResponseStatusTest()
        {
            // TODO unit test for the property 'ResponseStatus'
        }
        /// <summary>
        /// Test the property 'Room'
        /// </summary>
        [Fact]
        public void RoomTest()
        {
            // TODO unit test for the property 'Room'
        }

    }

}
