/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Akros.Htp.Exchange.Model;
using Akros.Htp.Exchange.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Akros.Htp.Exchange.Test.Model
{
    /// <summary>
    ///  Class for testing Country
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CountryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Country
        //private Country instance;

        public CountryTests()
        {
            // TODO uncomment below to create an instance of Country
            //instance = new Country();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Country
        /// </summary>
        [Fact]
        public void CountryInstanceTest()
        {
            // TODO uncomment below to test "IsType" Country
            //Assert.IsType<Country>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

    }

}
