/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Akros.Htp.Exchange.Model;
using Akros.Htp.Exchange.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Akros.Htp.Exchange.Test.Model
{
    /// <summary>
    ///  Class for testing Hotel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HotelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Hotel
        //private Hotel instance;

        public HotelTests()
        {
            // TODO uncomment below to create an instance of Hotel
            //instance = new Hotel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Hotel
        /// </summary>
        [Fact]
        public void HotelInstanceTest()
        {
            // TODO uncomment below to test "IsType" Hotel
            //Assert.IsType<Hotel>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Stars'
        /// </summary>
        [Fact]
        public void StarsTest()
        {
            // TODO unit test for the property 'Stars'
        }
        /// <summary>
        /// Test the property 'ZipCode'
        /// </summary>
        [Fact]
        public void ZipCodeTest()
        {
            // TODO unit test for the property 'ZipCode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Fact]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'HouseNumber'
        /// </summary>
        [Fact]
        public void HouseNumberTest()
        {
            // TODO unit test for the property 'HouseNumber'
        }
        /// <summary>
        /// Test the property 'Homepage'
        /// </summary>
        [Fact]
        public void HomepageTest()
        {
            // TODO unit test for the property 'Homepage'
        }
        /// <summary>
        /// Test the property 'Facilities'
        /// </summary>
        [Fact]
        public void FacilitiesTest()
        {
            // TODO unit test for the property 'Facilities'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Rooms'
        /// </summary>
        [Fact]
        public void RoomsTest()
        {
            // TODO unit test for the property 'Rooms'
        }

    }

}
