/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Akros.Htp.Exchange.Model;
using Akros.Htp.Exchange.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Akros.Htp.Exchange.Test.Model
{
    /// <summary>
    ///  Class for testing SearchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchRequest
        //private SearchRequest instance;

        public SearchRequestTests()
        {
            // TODO uncomment below to create an instance of SearchRequest
            //instance = new SearchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchRequest
        /// </summary>
        [Fact]
        public void SearchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchRequest
            //Assert.IsType<SearchRequest>(instance);
        }


        /// <summary>
        /// Test the property 'DestinationCountry'
        /// </summary>
        [Fact]
        public void DestinationCountryTest()
        {
            // TODO unit test for the property 'DestinationCountry'
        }
        /// <summary>
        /// Test the property 'DestinationPostalCode'
        /// </summary>
        [Fact]
        public void DestinationPostalCodeTest()
        {
            // TODO unit test for the property 'DestinationPostalCode'
        }
        /// <summary>
        /// Test the property 'DestinationCity'
        /// </summary>
        [Fact]
        public void DestinationCityTest()
        {
            // TODO unit test for the property 'DestinationCity'
        }
        /// <summary>
        /// Test the property 'HotelName'
        /// </summary>
        [Fact]
        public void HotelNameTest()
        {
            // TODO unit test for the property 'HotelName'
        }
        /// <summary>
        /// Test the property 'PriceFrom'
        /// </summary>
        [Fact]
        public void PriceFromTest()
        {
            // TODO unit test for the property 'PriceFrom'
        }
        /// <summary>
        /// Test the property 'PriceTo'
        /// </summary>
        [Fact]
        public void PriceToTest()
        {
            // TODO unit test for the property 'PriceTo'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'DateFrom'
        /// </summary>
        [Fact]
        public void DateFromTest()
        {
            // TODO unit test for the property 'DateFrom'
        }
        /// <summary>
        /// Test the property 'DateTo'
        /// </summary>
        [Fact]
        public void DateToTest()
        {
            // TODO unit test for the property 'DateTo'
        }
        /// <summary>
        /// Test the property 'NumberOfGuests'
        /// </summary>
        [Fact]
        public void NumberOfGuestsTest()
        {
            // TODO unit test for the property 'NumberOfGuests'
        }
        /// <summary>
        /// Test the property 'FacilityList'
        /// </summary>
        [Fact]
        public void FacilityListTest()
        {
            // TODO unit test for the property 'FacilityList'
        }

    }

}
