/*
 * OpenAPI definition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Akros.Htp.Exchange.Model;
using Akros.Htp.Exchange.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Akros.Htp.Exchange.Test.Model
{
    /// <summary>
    ///  Class for testing SearchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchResponse
        //private SearchResponse instance;

        public SearchResponseTests()
        {
            // TODO uncomment below to create an instance of SearchResponse
            //instance = new SearchResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchResponse
        /// </summary>
        [Fact]
        public void SearchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchResponse
            //Assert.IsType<SearchResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'DateFrom'
        /// </summary>
        [Fact]
        public void DateFromTest()
        {
            // TODO unit test for the property 'DateFrom'
        }
        /// <summary>
        /// Test the property 'DateTo'
        /// </summary>
        [Fact]
        public void DateToTest()
        {
            // TODO unit test for the property 'DateTo'
        }
        /// <summary>
        /// Test the property 'NumberOfGuests'
        /// </summary>
        [Fact]
        public void NumberOfGuestsTest()
        {
            // TODO unit test for the property 'NumberOfGuests'
        }
        /// <summary>
        /// Test the property 'Hotel'
        /// </summary>
        [Fact]
        public void HotelTest()
        {
            // TODO unit test for the property 'Hotel'
        }

    }

}
